listacomprasapp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
# urls de la aplicación /sitio
 
app_name = "listacomprasapp"

urlpatterns = [
    path('', views.home, name="home"),
    path(r'registro_usuario/', views.registro_usuario, name="registro_usuario"),
    path(r'listas/', views.listas, name="listas"),
    path(r'listas/agregar_lista/', views.agregar_lista, name='agregar_lista'),
    path(r'tiendas/', views.tiendas, name="tiendas"),
    path(r'tiendas/agregar_tienda/', views.agregar_tienda, name='agregar_tienda'),
    path(r'cerrar_sesion/', views.cerrar_sesion, name="cerrar_sesion"),
    path(r'tiendas/<int:id_tienda>/agregar_sucursal/', views.agregar_sucursal, name='agregar_sucursal'),
    path(r'tiendas/<int:id_tienda>/sucursales/', views.sucursales, name="sucursales"),
    path(r'tiendas/<int:id_tienda>/aprobar_tienda/', views.aprobar_tienda, name="aprobar_tienda"),
    path(r'listas/<int:id_lista>/detalle_lista/', views.detalle_lista, name='detalle_lista'),
    path(r'listas/<int:id_producto>/comprar_producto/', views.comprar_producto, name='comprar_producto'),
    path(r'listas/<int:id_producto>/eliminar_producto/', views.eliminar_producto, name='eliminar_producto'),
    path(r'listas/<int:id_lista>/agregar_producto/', views.agregar_producto, name='agregar_producto'),
]

sitioProyectoSemestral/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listacomprasapp.urls')),
]

listacomprasapp/models.py
from django.db import models

# Create your models here.
class Region(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Comuna(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Tienda(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    estado = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

#class TipoSucursal(models.Model):
#    nombre = models.CharField(max_length=100)
#
#    def __str__(self):
#        return self.nombre

class Sucursal(models.Model):
    nombre = models.CharField(max_length=100, null=True,blank=True)
    direccion = models.CharField(max_length=100)
    tienda = models.ForeignKey(Tienda, on_delete=models.CASCADE, default=1)
    comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE, null=True, blank=True)
    sucursal_fisica = models.BooleanField(default=False)

    def __str__(self):
        return self.direccion

class Producto(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    costo_presupuestado = models.IntegerField(null=True, blank=True)
    costo_real = models.IntegerField(null=True, blank=True)
    comentario = models.CharField(max_length=100, null=True, blank=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE, null=True, blank=True)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

class Lista(models.Model):
    nombre = models.CharField(max_length=100)
    duenno = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.nombre

class ListaProducto(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    lista = models.ForeignKey(Lista, on_delete=models.CASCADE)

    def __str__(self):
        return "Lista: " + str(self.lista) + ", Producto: " + str(self.producto)


listacomprasapp/forms.py
from django import forms
from . import models

class AgregarLista(forms.ModelForm):
    class Meta:
        model = models.Lista
        fields = ['nombre']

class AgregarProducto(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre','costo_presupuestado', 'comentario']

class ComprarProducto(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = ['costo_real', 'comentario', 'sucursal']

class AgregarTienda(forms.ModelForm):
    class Meta:
        model = models.Tienda
        fields = ['nombre']

class AgregarSucursal(forms.ModelForm):
    class Meta:
        model = models.Sucursal
        fields = ['sucursal_fisica','nombre', 'direccion', 'comuna' ]

listacomprasapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from . import forms
from .models import Lista, Producto, ListaProducto, Tienda, Sucursal



def home(request): #login
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('listacomprasapp:listas')
    else:
        form = AuthenticationForm()
    page_title = "Bichito"
    return render(request,'listacomprasapp/home.html', {'page_title': page_title, 'form':form})

def registro_usuario(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('listacomprasapp:listas')
    else:
        form = UserCreationForm()
    return render(request, 'listacomprasapp/registro_usuario.html', {'form' : form })

def cerrar_sesion(request):
    if request.method == 'POST':
        logout(request)
        return redirect('listacomprasapp:home')

def listas(request):
    id = request.user.id
    listas = Lista.objects.filter(duenno_id=id)
    
    return render(request, 'listacomprasapp/listas.html', {'listas':listas})

def tiendas(request):
    if request.user.is_staff:
        tiendas = Tienda.objects.all()
    else:
        tiendas = Tienda.objects.filter(estado=True)
    return render(request, 'listacomprasapp/tiendas.html', {'tiendas':tiendas})

def sucursales(request, id_tienda):
    sucursales = Sucursal.objects.filter(tienda_id=id_tienda)
    tienda = Tienda.objects.filter(id=id_tienda)
    return render(request, 'listacomprasapp/sucursales.html', {'sucursales':sucursales, 'id_tienda':id_tienda, 'tienda':tienda})

@login_required(login_url="listacomprasapp:home")
def agregar_sucursal(request, id_tienda):
    tiendas = Tienda.objects.filter(id = id_tienda)
    if request.method == 'POST':
        form = forms.AgregarSucursal(request.POST)
        if form.is_valid():
            instancia = form.save(commit=False)
            tienda = get_object_or_404(Tienda, id=id_tienda)
            instancia.tienda = tienda
            instancia.save()
            return redirect('listacomprasapp:tiendas')
    else:
        form = forms.AgregarSucursal()
    return render(request, 'listacomprasapp/agregar_sucursal.html', {'form':form,'tiendas':tiendas})

@login_required(login_url="listacomprasapp:home")
def agregar_tienda(request):
    if request.method == 'POST':
        form = forms.AgregarTienda(request.POST)
        if form.is_valid():
            instancia = form.save(commit=False)
            instancia.save()
            return redirect('listacomprasapp:tiendas')
    else:
        form = forms.AgregarTienda()
    return render(request, 'listacomprasapp/agregar_tienda.html', {'form':form})

@login_required(login_url="listacomprasapp:home")
def aprobar_tienda(request, id_tienda):
    tienda = get_object_or_404(Tienda, id=id_tienda)
    tienda.estado = True
    tienda.save(update_fields=["estado"])
    return redirect('listacomprasapp:tiendas')

@login_required(login_url="listacomprasapp:home")
def agregar_lista(request):
    if request.method == 'POST':
        form = forms.AgregarLista(request.POST)
        if form.is_valid():
            instancia = form.save(commit=False)
            instancia.duenno_id = request.user.id
            instancia.save()
            return redirect('listacomprasapp:listas')
    else:
        form = forms.AgregarLista()
    return render(request, 'listacomprasapp/agregar_lista.html', {'form':form})

@login_required(login_url="listacomprasapp:home")
def agregar_producto(request, id_lista):
    if request.method == 'POST':
        form = forms.AgregarProducto(request.POST)
        if form.is_valid():
            instancia = form.save(commit=False)
            instancia.save()

            auxLista = get_object_or_404(Lista, id=id_lista)
            lista_producto = ListaProducto(producto=instancia,lista=auxLista)
            lista_producto.save()
            return redirect('listacomprasapp:detalle_lista', id_lista=id_lista)
    else:
        form = forms.AgregarProducto()
    return render(request, 'listacomprasapp/agregar_producto.html', {'form':form})

@login_required(login_url="listacomprasapp:home")
def comprar_producto(request, id_producto=None):
    instancia = get_object_or_404(Producto, id=id_producto)
    form = forms.ComprarProducto(request.POST or None, instance=instancia)
    if form.is_valid():
        instancia = form.save(commit=False)
        instancia.estado = False #True: Pendiente, False: Comprado
        instancia.save()
        lista = Lista.objects.get(listaproducto__producto=id_producto)

        return redirect("listacomprasapp:detalle_lista", id_lista=lista.id)
    contexto = {
        "nombre":instancia.nombre,
        "costo_real":instancia.costo_real,
        "comentario":instancia.comentario,
        "sucursal":instancia.sucursal,
        "producto":instancia,
        "form":form,
    }
    return render(request, 'listacomprasapp/comprar_producto.html', contexto)

@login_required(login_url="listacomprasapp:home")
def eliminar_producto(request, id_producto=None):
    instancia = get_object_or_404(Producto, id=id_producto)
    instancia.delete()  
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required(login_url="listacomprasapp:home")
def detalle_lista(request, id_lista):
    lista = Lista.objects.filter(id = id_lista)
    productos = Producto.objects.filter(listaproducto__lista=id_lista)
    total_costo_presupuestado=0
    total_costo_real=0
    productos_comprados=0
    productos_pendientes=0

    for producto in productos:
        if producto.estado == True:
            total_costo_presupuestado=total_costo_presupuestado+producto.costo_presupuestado
            productos_pendientes=productos_pendientes+1
        else:
            total_costo_real=total_costo_real+producto.costo_real
            total_costo_presupuestado=total_costo_presupuestado+producto.costo_presupuestado
            productos_comprados=productos_comprados+1

    contexto = {
        "productos":productos,
        "total_costo_presupuestado":total_costo_presupuestado,
        "total_costo_real":total_costo_real,
        "id_lista":id_lista,
        "lista":lista,
        "productos_comprados": productos_comprados,
        "productos_pendientes": productos_pendientes,
    }
    return render(request,'listacomprasapp/detalle_lista.html',contexto)

listacomprasapp/templates/listacomprasapp/agregar_lista.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <form class="form-app col-sm-6" action="{% url 'listacomprasapp:agregar_lista' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <div>
            <button class="btn btn-primary" type="submit">Agregar Lista</button>
        </div>
    </form>
</div>
{% endblock %}

listacomprasapp/templates/listacomprasapp/agregar_producto.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="row justify-content-center">
<form class="form-app col-sm-6" action="" method="POST">
    <h1 class="h5">Agregar Producto</h1>
    {% csrf_token %}
    {{ form }}
    <input type="hidden" value="{{ lista.id }}">
    <button class="btn btn-primary" type="submit">AGREGAR PRODUCTO</button>
</form>
</div>
{% endblock %}

listacomprasapp/templates/listacomprasapp/agregar_sucursal.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
{{tienda}}

<div class="row justify-content-center">
    
    <form class="form-app col-sm-6 d-none" id="nueva-sucursal" method="POST">
            <h1 class="h5">Agregar sucursal para {%for t in tiendas%}{{t.nombre}}{%endfor%}</h1>
        {% csrf_token %}
        {{ form }}
        <div>
            <button class="btn btn-primary" type="submit">Agregar Sucursal</button>
        </div>
    </form>
    <script>
        $(document).ready(function(){
            
            $("label[for='id_sucursal_fisica']").html("<i class='far fa-square'></i> Tienda Física");
            $("#id_comuna").hide();
            $("label[for='id_comuna']").hide();
            $("label[for='id_direccion']").text('Web');
            $("#id_direccion").attr("type", 'url');
            
            $(".form-app").removeClass('d-none');
            
            $("#id_sucursal_fisica").on("change", function(){
                if($(this).is(":checked")){
                    $("label[for='id_sucursal_fisica']").html("<i class='far fa-check-square'></i> Tienda Física");
                    $("#id_comuna").show();
                    $("label[for='id_comuna']").show();
                    $("label[for='id_direccion']").text('Dirección');
                    $("#id_direccion").attr("type", 'text');
                }else{
                    $("label[for='id_sucursal_fisica']").html("<i class='far fa-square'></i> Tienda Física");
                    $("#id_comuna").hide();
                    $("label[for='id_comuna']").hide();
                    $("label[for='id_direccion']").text('Web').attr("type", 'url');
                    $("#id_direccion").attr("type", 'text');
                }
                
            })
        })
    </script>
</div>
{% endblock %}

listacomprasapp/templates/listacomprasapp/agregar_tienda.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <form class="form-app col-sm-6" action="{% url 'listacomprasapp:agregar_tienda' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <div>
            <button class="btn btn-primary" type="submit">Agregar Tienda</button>
        </div>
    </form>
</div>
{% endblock %}

listacomprasapp/templates/listacomprasapp/comprar_producto.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-6">
        <h1>{{producto.nombre}}</h1>
        <p>Costo Presupuestado: {{producto.costo_presupuestado}}</p>
        <form class="form-app" action="{% url 'listacomprasapp:comprar_producto' id_producto=producto.id %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-primary" type="submit">COMPRAR</button>
        </form>
    </div>
</div>


{% endblock %}

listacomprasapp/templates/listacomprasapp/detalle_lista.html

{% extends 'base/base.html' %}
{%load humanize%}
{% block title %}{{page_title}}{% endblock %}

{% block content %}
{% if total_costo_presupuestado < total_costo_real %}
<div class="alert alert-danger" role="alert">
    Costo Real es mayor al Costo estimado
</div>
{% endif %}

<div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
        <div class="row">
            <h1 class="col-12 h5">
                {%for l in lista%}{{l.nombre}}{%endfor%}
                <span class="badge badge-dark">{{productos|length}}</span>
            </h1>
            <div class="col-sm-6">
                    <a href="#" class="badge badge-primary">{{productos_comprados}}</a> comprados
            </div>
            <div class="col-sm-6">
                    <a href="#" class="badge badge-primary">{{productos_pendientes}}</a> pendientes
            </div>
        </div>
        <a class="btn btn-primary" href="{% url 'listacomprasapp:agregar_producto' id_lista=id_lista %}">
                <i class="fas fa-archive"></i> Agregar Producto
            </a>
    </div>
    <ul class="list-group list-group-flush d-flex flex-column">
        {% for producto in productos %}
        {% if producto.estado == True %}
        <li class="list-group-item order-1">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h4 class="h5"> {{ producto.nombre }}</h4>
                    Estimado <i class="fas fa-dollar-sign"></i>{{producto.costo_presupuestado|intcomma}}
                </div>
                <div class="btn-group">
                    <a class="btn btn-success" href="{% url 'listacomprasapp:comprar_producto' id_producto=producto.id %}">
                        <i class="far fa-money-bill-alt"></i> COMPRAR
                    </a>
                    <a class="btn btn-danger" href="{% url 'listacomprasapp:eliminar_producto' id_producto=producto.id %}">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </div>
            </div>
        </li>
        {%else%}
        <li class="list-group-item order-2">
            <div class="row justify-content-between align-items-center">
                <div class="col">
                    <h4 class="h5"><i class="fas fa-check"></i> {{ producto.nombre }}</h4>
                    <div class="row">
                        <div class="col-sm">
                            Estimado <i class="fas fa-dollar-sign"></i><strong>{{producto.costo_presupuestado|intcomma}}</strong>
                        </div>
                        <div class="col-sm">
                            Costo Real <i class="fas fa-dollar-sign"></i><strong>{{producto.costo_real|intcomma}}</strong>
                        </div>
                    </div>  
                </div>
                <div class="btn-group">
                    <a class="btn btn-warning" href="{% url 'listacomprasapp:comprar_producto' id_producto=producto.id %}">
                        <i class="fas fa-pen"></i> Editar Compra
                    </a>
                    <a class="btn btn-danger" href="{% url 'listacomprasapp:eliminar_producto' id_producto=producto.id %}">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </div>
            </div>
        </li>
        {% endif %}
        {% endfor %}
        <li class="list-group-item order-3">
            <div class="row text-right">
                <div class="col-sm-6">Total Estimado <i class="fas fa-dollar-sign"></i> <strong>{{total_costo_presupuestado|intcomma}}</strong></div>
                <div class="col-sm-6">Total Real<i class="fas fa-dollar-sign"></i><strong>{{total_costo_real|intcomma}}</strong></div>
        </li>
    </ul>
</div>


{% endblock %}

listacomprasapp/templates/listacomprasapp/home.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="row justify-content-center">
    {% if user.is_authenticated %}
    <div class="col-sm-6">
    <!--logout-->
    <h1>
        <small class="text-muted">
            <i class="fas fa-user"></i>
        </small> 
        {{ user.get_username}} 
    </h1>
    {%if user.is_staff %}
        <div>
            <small class="badge badge-warning">
                <i class="fas fa-star"> </i> SU 
            </small>
        </div>    
    {%endif%}
    <p>{{user.email}}</p> 
        
    <form action="{% url 'listacomprasapp:cerrar_sesion' %}" method="POST">
        {% csrf_token %}
        
        <button class="btn btn-success" type="submit">Cerrar Sesion</button>
    </form>
</div>
    {% else %}
    <!-- INICIAR SESION -->
    <form class="form-app col-sm-6" action="{% url 'listacomprasapp:home' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <div class="row">
            <div class="col">
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button type="submit" class="btn btn-primary" value="Login">INICIAR SESION</button>
                <a class="btn btn-link" href="{% url 'listacomprasapp:registro_usuario' %}">Registrarse</a>
            </div>
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}

listacomprasapp/templates/listacomprasapp/listas.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">

        {% if listas|length > 0 %}
        <div class="col-12">
            <!-- CONTENEDOR LISTAS -->
           
            <div class="d-flex justify-content-between mb-3">
                <h1 class="h4">Mis Listas <span class="badge badge-dark">{{listas|length}}</span></h1>
                <a class="btn btn-primary" href="{% url 'listacomprasapp:agregar_lista' %}">Agregar Lista</a>
            </div>

            <ul class="list-group">
                {% for lista in listas %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between align-items-center">
                        <!-- ITEM LISTA -->
                        <a href="{% url 'listacomprasapp:detalle_lista' id_lista=lista.id %}">
                            <h2>{{ lista.nombre }}</h2>
                        </a>
                        <a class="btn btn-success" 
                        href="{% url 'listacomprasapp:agregar_producto' id_lista=lista.id %}">
                            Agregar Producto
                        </a>
                    </div> <!-- FIN ITEM LISTA -->
                </li>
                {% endfor %}
            </ul>
        </div> <!-- FIN CONTENEDOR LISTAS -->
        {% else %}
        <div class="col-12">
            <div class="jumbotron">
                <h1 class="display-4">Hola</h1>
                <p>Aun no tienes ninguna lista creada, te invitamos a crear tu primera lista haciendo Clic en el "Crear
                    una nueva lista".</p>
                <a class="btn btn-primary" href="{% url 'listacomprasapp:agregar_lista' %}">Crear una Nueva Lista</a>

            </div>

        </div>
        {% endif %}
    </div>
</div>



{% endblock %}

listacomprasapp/templates/listacomprasapp/registro_usuario.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <form class="form-app col-sm-6" action="" method="post">
        <div class="col-12">
            {% csrf_token %}
            {{ form }}
        </div>
        <div class="col-12">
            <button class="btn btn-primary" type="submit" value="Signup">Registrarse</button>
            <a class="btn" href="/" value="Signup">Iniciar Sesión</a>
        </div>
    </form>
</div>
{% endblock %}

listacomprasapp/templates/listacomprasapp/sucursales.html
{% extends 'base/base.html' %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h1>
            {% for t in tienda %}{{t.nombre}}{%endfor%}
            {% if sucursales|length > 0 %}
                <span class="badge badge-dark">
                    {{sucursales|length}}
                </span>
            {%endif%}
        </h1>
            {% if sucursales|length > 0 and user.is_authenticated %}
            <a class="btn btn-primary" 
                href="{% url 'listacomprasapp:agregar_sucursal' id_tienda %}">Agregar Sucursal</a>
            {% endif %}
    </div>
    <div class="col-12">
        {% if sucursales|length > 0 and user.is_authenticated %}
            <ul class="list-group">
                {% for sucursal in sucursales %}
                    <li class="list-group-item"> 
                        <div>  
                            <p>
                            {% if sucursal.sucursal_fisica == True %}
                                {{sucursal.nombre}} 
                                <i class="fas fa-map-marker-alt"></i>
                                {{sucursal.direccion}}, {{sucursal.comuna}}
                            {% else %}
                                {{sucursal.nombre}} 
                                <i class="fas fa-globe-americas"></i>
                                {{sucursal.direccion}}
                            {% endif %}   
                            </p>
                            
                
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="jumbotron">
                {% if user.is_authenticated %}
                <h1 class="display-4">Aun no tienes sucursales</h1>
                
                <p class="lead">
                        <a class="btn btn-primary" 
                        href="{% url 'listacomprasapp:agregar_sucursal' id_tienda %}">Agregar Sucursal</a>
                </p>
                {%else%}
                <h1 class="display-4">Lo sentimos, aun no hay sucursales</h1>
                {% endif %}
              </div>
        {% endif %}
    </div>
</div>
{% endblock %}

listacomprasapp/templates/listacomprasapp/tiendas.html
{% extends 'base/base.html' %}

{% block title %}Tiendas{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12 d-flex justify-content-between">
        <h1>Tiendas </h1>
        <div> 
            {% if user.is_authenticated %}  
        <a class="btn btn-primary" href="{% url 'listacomprasapp:agregar_tienda' %}">Agregar Tienda</a>
        {% endif %}
    </div>
    </div>
    <div class="col-12">
        <ul class="list-group">
            {% for tienda in tiendas %}
            <li class="list-group-item">
                <h4>{{tienda.nombre}}
                    {% if user.is_authenticated %}
                    {%  if tienda.estado == True %}
                        <span class="badge badge-dark">
                            <i class="fas fa-check"></i> Aprobado
                        </span>
                    {% else %}
                        <span class="badge badge-danger">Pendiente de aprobación</span>
                    {% endif %}
                    {%endif%}
                </h4>
                {% if tienda.estado %}
                <a  class="btn btn-success" 
                    href="{% url 'listacomprasapp:sucursales' id_tienda=tienda.id %}">
                    <i class="fas fa-store"></i> Ver Sucursales
                </a>  
                {%endif%}


                {% if user.is_staff %}
                    {% if tienda.estado == False %}
                       <a class="btn btn-info" href="{% url 'listacomprasapp:aprobar_tienda' id_tienda=tienda.id %}">
                           Aprobar Tienda
                        </a>
                    {% endif %}
                {% endif %}
            </li>
            {% endfor %}
        </ul>


    </div>
</div>
<br><br>

{% endblock %}